name: Demo Pipeline

on:
  schedule:
    - cron: '0,10,20,30,40,50 * * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Manual'  

jobs:
  build:
    runs-on: windows-latest
    steps:
    - run: mkdir -p artifactApp
    - run: mkdir -p artifactTests
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: test app with dotnet
      run: dotnet test WebApp/TestSite.sln
    - name: Publish app with dotnet
      run: dotnet publish WebApp/TestSite.sln -c Release -o ${{github.workspace}}/artifactApp
    - name: Build automated tests with dotnet
      run: dotnet build TestAutomation/DemoTests.sln -o "${{github.workspace}}/artifactTests"
    - name: Upload app artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: app
        path: artifactApp
    - name: Upload test artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: tests
        path: artifactTests

  deployToLower:
    if: github.ref == 'refs/heads/master'
    needs: build
    environment: lower
    runs-on: windows-latest
    steps:
      - name: download app
        uses: actions/download-artifact@v1
        with:
          name: app
          path: artifactApp
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: "TTWDevOpsLower"
          publish-profile: ${{ secrets.LowerPubProfile  }} 
          package: 'artifactApp'
          
  testInLower:
    needs: deployToLower
    runs-on: windows-latest
    steps:
      - name: download tests
        uses: actions/download-artifact@v1
        with:
          name: tests
          path: artifactTests
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: Setup VSTest Path
        uses: darenm/Setup-VSTest@v1 
        
      - name: Updated Chrome
        run: |
          choco install googlechrome -y

     # - name: VSTest
      #  run: vstest.console.exe artifactTests\tests.dll --TestCaseFilter:TestCategory=Regression /logger:"trx;LogFileName=${{github.workspace}}/artifactTests/logs/results.trx" --Settings:artifactTests\Parallel.RunSettings 
        
      - name: run tests
        shell: cmd
        run: dotnet vstest artifactTests\tests.dll --TestCaseFilter:TestCategory=Regression /logger:"trx;LogFileName=${{github.workspace}}/artifactTests/logs/results.trx" --Settings:artifactTests\ParallelHigher.RunSettings  
        #run: dotnet vstest artifactTests\tests.dll --TestCaseFilter:TestCategory=Regression /logger:"trx;LogFileName=${{github.workspace}}/artifactTests/logs/results.trx" --Settings:artifactTests\Parallel.RunSettings  -- TestRunParameters.Parameter(name=\"SeleniumMaqs:Browser\",value=\"Chrome\") TestRunParameters.Parameter(name=\"SeleniumMaqs:WebSiteBase\", value=\"https://ttwdevopshigher.azurewebsites.net\")

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: lowerTestResults
          path: artifactTests\logs
  deployToHigher:
    needs: testInLower
    runs-on: windows-latest
    environment: higher
    steps:
      - name: download app
        uses: actions/download-artifact@v1
        with:
          name: app
          path: artifactApp
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: "TTWDevOpsHigher"
          publish-profile: ${{ secrets.HigherPubProfile  }} 
          package: 'artifactApp'
          
  testInHigher:
    needs: deployToHigher
    runs-on: windows-latest
    steps:
      - name: download tests
        uses: actions/download-artifact@v1
        with:
          name: tests
          path: artifactTests
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
        
      - name: Updated Chrome
        run: |
          choco install googlechrome -y
          
      - name: run tests
        shell: cmd
        run: dotnet vstest artifactTests\tests.dll --TestCaseFilter:TestCategory=Regression /logger:"trx;LogFileName=${{github.workspace}}/artifactTests/logs/results.trx" --Settings:artifactTests\ParallelHigher.RunSettings  
        #run: dotnet vstest artifactTests\tests.dll --TestCaseFilter:TestCategory=Regression /logger:"trx;LogFileName=${{github.workspace}}/artifactTests/logs/results.trx" --Settings:artifactTests\Parallel.RunSettings  -- TestRunParameters/Parameter[contains(@name,'SeleniumMaqs:Browser')]/@value="Chrome"  TestRunParameters/Parameter[contains(@name,'SeleniumMaqs:WebSiteBase')]/@value="https://ttwdevopshigher.azurewebsites.net"
      
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: higherTestResults
          path: artifactTests\logs
