name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - run: mkdir -p artifactApp
    - run: mkdir -p artifactTests
      
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build and test app with dotnet
      run: dotnet test WebApp/TestSite.sln /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /maxcpucount:1 /p:configuration="Release" /p:DesktopBuildPackageLocation="${{github.workspace}}/artifactApp/package.zip"
    - name: Build and test test with dotnet
      run: dotnet build /TestAutomation/DemoTests.sln -o "${{github.workspace}}/artifactTests"
    - name: Upload app artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: app
        path: artifactApp
    - name: Upload test artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: tests
        path: artifactTests
